### ISSUE TITLE
Wrong redirection on login/logout at HTTPS-Sites

### ISSUE THREAD

**Issue by b-vetter** [Eole-dev/authphpbb3#2]
All my sites using HTTPS. Also my phpBB-board and my DokuWiki.
My phpBB forum (3.1) is located on the root-path of my domain. The wiki is at /wiki/.

The SSO-like "session transfer" works perfekt, but if the user click "Login via Forum" or "Logout" on the Wiki-Page, the site redirect to https://myurl.com:80.
HTTPS on Port 80? This doesn't work!

You can try it on my site: https://www.amzecho.de/wiki/start?do=login

Can you fix it or is it a configuration mistake?

Thanks and best regards
Benjamin

**Comment by EoleDevel** [comment]
Hi,

In your phpBB configuration, check you configured the server port and the value 443 is assigned.

**Comment by Eole-dev** [comment]
Hi,

Check you have configured the server port and server protocol in your phpBB installation: it should be **443** and **https://** respectively (not empty).

In order to reflect the change in DokuWiki, you need to disable the cache of the authphpBB3 plugin by setting the value to **0**. Then, try to login and logout from your DokuWiki, the redirection should work. Finally, you can enable the plugin cache again.

**Comment by b-vetter** [comment]
Perfect, that works!
Thank you very much.

**Comment by edgimar** [comment]
I ran into the same problem (I changed the phpbb protocol and port settings _after_ setting up the plugin), and spent a long time trying to fix the problem before finding this issue.  Clearing the cache helped.  This tip should be included on the https://www.dokuwiki.org/plugin:authphpbb3 page below the text:

    If you are not using the default protocol (http) and the default port (80), check you have configured the server port and server protocol in your phpBB installation.
